### ISSUE TITLE
搭建个人博客

### ISSUE THREAD

**Issue by yuyuyu-github** [yuyuyu-github/LifeTime#100]
# 动机

- 个人博客可以完全受自己掌控，不会被平台干涉
- 个人博客是我文章的输出集中处，通过输出汇总我的知识结晶。
- 通过写作反向考验自己的知识输出能力
- [2022最新版保姆级Hexo+github搭建个人博客并绑定自己的域名_哔哩哔哩_bilibili]
-  [写作，为什么如此重要 - 知乎](https://zhuanlan.zhihu.com/p/19713784)

# 愿景

-  找到一个优质的不需要自己花大量精力修改的博客框架，根据框架搭建起博客

# 博客搭建过程

- [x] 了解现有博客框架，从中挑选一个适合你的（功能强大、访问快速、社区活跃、发文简单，主题好看）
- [x] 找到优质博客搭建教程
- [x] #108
- [x] #107
- [x] 学习腾讯云的基本使用
- [x] 本机连接服务器
- [x] 安装Docker
- [x] 安装Halo博客
- [x] 配置域名的DNS解析
- [ ] 配置反向代理
- [ ] 美化

# 参考
- [搭博客到底选什么框架？Hexo还是Hugo？Typecho还是Wordpress？_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1cv411N7kz?p=7&vd_source=267912aeeecbd49d6471a2aabb11aaec)

**Comment by qifengle1998** [comment]
- [写作，为什么如此重要 - 知乎](https://zhuanlan.zhihu.com/p/19713784)
- [【2022最新版】保姆级Hexo+github搭建个人博客并绑定自己的域名_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1NY4y1C7Ng?spm_id_from=333.337.search-card.all.click&vd_source=267912aeeecbd49d6471a2aabb11aaec)

**Comment by qifengle1998** [comment]
# 参考博客
- [小令童鞋](https://www.zeekling.cn/)
- [标签 | 闪烁之狐](http://blinkfox.com/tags)

**Comment by qifengle1998** [comment]
[技术分享记录生活](https://www.zjhuiwan.cn/index)

**Comment by qifengle1998** [comment]
不要想着第一次就找到自己喜欢的博客。
先选halo，搭建起来再说

**Comment by yuyuyu-github** [comment]
48元买了第一个轻量级云服务器
![image](https://user-images.githubusercontent.com/37429029/176335024-e3d13885-f5aa-48bb-9da2-27af4b8f6571.png)

**Comment by yuyuyu-github** [comment]
28首年买了人生第一个域名 haiyu-blog.com
![image](https://user-images.githubusercontent.com/37429029/176341953-ff4feb1d-46c0-4825-9c0c-995fbe59f13a.png)

**Comment by yuyuyu-github** [comment]
安装halo博客后，无法通过ip访问
![image](https://user-images.githubusercontent.com/37429029/176370882-343e6b67-c8c7-44bd-99a4-5df650a9de22.png)

**Comment by yuyuyu-github** [comment]
> docker安装halo报错 `Error response from daemon: driver failed programming external connectivity on endpoint halo (e641a0192be7c8efef88355964b373858b522a4387ed546756da3717e7bc64bc): (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8090 -j DNAT --to-destination 172.17.0.2:8090 ! -i docker0: iptables: No chain/target/match by that name. `

删除容器，删除创建的文件夹。
重新用官方文档 halo+mysql安装解决

**Comment by yuyuyu-github** [comment]
安装halo博客后，无法通过ip访问
![image](https://user-images.githubusercontent.com/37429029/176370882-343e6b67-c8c7-44bd-99a4-5df650a9de22.png)

**Comment by yuyuyu-github** [comment]
> 安装halo博客后，无法通过ip访问 ![image](https://user-images.githubusercontent.com/37429029/176370882-343e6b67-c8c7-44bd-99a4-5df650a9de22.png)

删除容器重新创建，然后重启计算机，登录进来了

**Comment by yuyuyu-github** [comment]
成功进入博客的后台管理系统
![Uploading image.png…]()

**Comment by yuyuyu-github** [comment]
域名解析失败
![image](https://user-images.githubusercontent.com/37429029/176386767-39d619c5-7bab-4ba0-8608-f7ff0945bb5c.png)

**Comment by yuyuyu-github** [comment]
> 域名解析失败 ![image](https://user-images.githubusercontent.com/37429029/176386767-39d619c5-7bab-4ba0-8608-f7ff0945bb5c.png)

不知道为什么现在只能通过halo前缀访问了

**Comment by yuyuyu-github** [comment]
通过复制这个博客里面的配置
成功进入到博客
![image](https://user-images.githubusercontent.com/37429029/176388757-2e1f5058-6d5b-4ee7-9485-d97ac049fb5a.png)

**Comment by yuyuyu-github** [comment]
不知道为什么，直接在博客下载主题特别慢，只能先用git下载到本地上传了

**Comment by yuyuyu-github** [comment]
基本的个人博客搭建完毕
![image](https://user-images.githubusercontent.com/37429029/176394476-733a7c32-e820-4ee4-a322-0e9874468136.png)

**Comment by yuyuyu-github** [comment]
做了备案，烦死了，真麻烦，还要拍丑照
![image](https://user-images.githubusercontent.com/37429029/177353718-306cb825-cc95-45de-a8d2-9d3d26e1d1cd.png)
