### ISSUE TITLE
研究项目业务模块的学习流程

### ISSUE THREAD

**Issue by yuyuyu-github** [yuyuyu-github/LifeTime#31]
- [x] #39
- [x] #40
- [x] #41
- [ ] 从宏观上理解业务流程，并记录自己的理解
- [ ] 补齐业务流程涉及的知识点，做到能够看懂代码
- [ ] 总结对应的 业务流程、框架知识、Java语法

# 2022-6-28 学完三级分类
出于现在时间已经快到7月份，我的总体课程有339级，而我才学到59级。
并且基础篇前端内容较多。
-**所以我的决定是，快速过完基础篇，目标可以理清从前端到后端地调用流程并输出即可。**
具体用到的语法和业务逻辑，我先不去细究。 快速过完基础篇 100集。
- 根据他人的笔记理一遍流程，不用专门做笔记

**Comment by qifengle1998** [comment]
目前学习完了三级分类，对项目的学习过程感觉迷茫
