### ISSUE TITLE
三级分类

### ISSUE THREAD

**Issue by yuyuyu-github** [yuyuyu-github/LifeTime#69]
# 课程模块评价：
80%讲的都是前端，并且是拖拽这种业务逻辑，目前学习价值不大

**Comment by qifengle1998** [comment]
product服务运行成功
![image](https://user-images.githubusercontent.com/37429029/175796331-40dcbc79-0610-48d0-a803-0f7ad90f3aad.png)

**Comment by qifengle1998** [comment]
具体业务代码看不明白，需要两个前置知识：
- [ ] Stram流式编程（Java8新特性）
- [ ] lambda表达式

**Comment by qifengle1998** [comment]
lambda表达式

**Comment by qifengle1998** [comment]
我觉得看代码的时候，多个页签，切换来切换去特别麻烦，想看看有没有什么页签能简化查看多个代码，来回跳转的问题

**Comment by qifengle1998** [comment]
我之前弄错了，service是写具体业务逻辑的， controller是写接受请求和返回数据的

**Comment by qifengle1998** [comment]
service、serviceimpl
[(12条消息) Springboot中Service+ServiceImpl的结构解析_O夫子的博客-CSDN博客_service serviceimpl](https://blog.csdn.net/qq_35921925/article/details/107178841)

**Comment by qifengle1998** [comment]
这里使用了mybatis-plus，我应该复制一下
![image](https://user-images.githubusercontent.com/37429029/175802601-7400d4a9-1a1a-4617-b445-80fc938d40b0.png)

**Comment by qifengle1998** [comment]
业务代码没看太懂，看弹幕好像就是写了一个简单的3层嵌套，只不过涉及了stream流和lambda表达式

**Comment by qifengle1998** [comment]
application.yml的值，是不是都可以放到配置中心？

**Comment by qifengle1998** [comment]
在用restful tool 测试批量修改功能的时候，报错
Cannot deserialize instance of `com.atguigu.gulimall.product.entity.CategoryEntity[]` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.atguigu.gulimall.product.entity.CategoryEntity[]` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 1]

**Comment by qifengle1998** [comment]
> Cannot deserialize instance of `com.atguigu.gulimall.product.entity.CategoryEntity[]` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.atguigu.gulimall.product.entity.CategoryEntity[]` out of START_OBJECT token
>  at [Source: (PushbackInputStream); line: 1, column: 1]

原因，后端需要一个数组，我发的是一个单个的值
Cannot deserialize instance of `com.atguigu.gulimall.product.entity.CategoryEntity[]` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.atguigu.gulimall.product.entity.CategoryEntity[]` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 1]

**Comment by qifengle1998** [comment]
报错`JSON parse error: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (PushbackInputStream); line: 1, column: 1]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (PushbackInputStream); line: 1, column: 1])
 at [Source: (PushbackInputStream); line: 1, column: 57] (through reference chain: java.lang.Object[][2])`

**Comment by qifengle1998** [comment]
> 报错`JSON parse error: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (PushbackInputStream); line: 1, column: 1]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (PushbackInputStream); line: 1, column: 1]) at [Source: (PushbackInputStream); line: 1, column: 57] (through reference chain: java.lang.Object[][2])`

json数组没输入正确

**Comment by qifengle1998** [comment]
报错
![image](https://user-images.githubusercontent.com/37429029/175854982-8e4e3eae-bcd8-41e9-ab16-521aa5f07a1b.png)

**Comment by qifengle1998** [comment]
> 报错 ![image](https://user-images.githubusercontent.com/37429029/175854982-8e4e3eae-bcd8-41e9-ab16-521aa5f07a1b.png)

暂时没有找到好的解决方法
