### ISSUE TITLE
跟社保局打电话，确认社保事项

### ISSUE THREAD

**Issue by yuyuyu-github** [yuyuyu-github/LifeTime#8]

**Comment by qifengle1998** [comment]
1。 可不可以断交，有什么影响？ 医保，社保一起交吗
2. 如果在其他城市找工作，后续交社保有什么还是正常交吗？有没有什么需要注意的位置，办手续
3. 现在我要交多少钱，每个月多少号交？  缴纳方式。

**Comment by yuyuyu-github** [comment]
放弃了，在家三个月了，也没交社保，还是算了。反正也交不起
